### ISSUE TITLE
Polygon coverage node crashes when wall_distance not zero

### ISSUE THREAD

**Issue by Remo-Steiner** [ethz-asl/polygon_coverage_planning#26]
**By using the following polygon definition:**

polygon:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'world'
  polygon:
    holes:
    - points:
      - {x:  12.0, y:  -4.3, z:   3.0}
      - {x:  12.0, y: -11.3, z:   3.0}
      - {x:   2.7, y: -11.3, z:   3.0}
      - {x:   2.7, y:  -4.3, z:   3.0}
    hull:
      points:
      - {x:  22.0, y:   5.7, z:   3.0}
      - {x:  22.0, y: -21.3, z:   3.0}
      - {x:  -7.3, y: -21.3, z:   3.0}
      - {x:  -7.3, y:   5.7, z:   3.0}

**and the parameter wall_distance not being zero, the polygon coverage node crashes.
Console output:**

roslaunch polygon_coverage_ros coverage_planner.launch
... logging to /home/rsteiner/.ros/log/83c9a626-e8da-11e9-a211-7c763585f93f/roslaunch-rstvivo-2599.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rstvivo:34963/

SUMMARY
CLEAR PARAMETERS
 * /coverage_planner/

PARAMETERS
 * /coverage_planner/a_max: 1.0
 * /coverage_planner/cost_function_type: 1
 * /coverage_planner/decomposition_type: 0
 * /coverage_planner/latch_topics: True
 * /coverage_planner/lateral_footprint: 1.0
 * /coverage_planner/lateral_fov: 0.84
 * /coverage_planner/lateral_overlap: 0.6
 * /coverage_planner/offset_polygons: False
 * /coverage_planner/polygon/header/frame_id: world
 * /coverage_planner/polygon/header/seq: 0
 * /coverage_planner/polygon/header/stamp/nsecs: 0
 * /coverage_planner/polygon/header/stamp/secs: 0
 * /coverage_planner/polygon/polygon/holes: [{'points': [{'y'...
 * /coverage_planner/polygon/polygon/hull/points: [{'y': 5.7, 'x': ...
 * /coverage_planner/publish_plan_on_planning_complete: False
 * /coverage_planner/publish_visualization_on_planning_complete: True
 * /coverage_planner/sensor_model_type: 1
 * /coverage_planner/set_polygon_from_rviz: True
 * /coverage_planner/set_start_goal_from_rviz: True
 * /coverage_planner/sweep_single_direction: False
 * /coverage_planner/v_max: 3.0
 * /coverage_planner/wall_distance: 1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    coverage_planner (polygon_coverage_ros/coverage_planner)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[rviz-1]: started with pid [2615]
process[coverage_planner-2]: started with pid [2616]
[ INFO] [1570437712.789966488]: Setting polygon altitude height to first z variable: 3
[ INFO] [1570437712.790666128]: Successfully loaded polygon.
[ INFO] [1570437712.790686737]: Altitude: 3 m
[ INFO] [1570437712.790694143]: Global frame: world
[ INFO] [1570437712.790726507]: Polygon:4 22 5.7 22 -21.3 -7.3 -21.3 -7.3 5.7  1 4 12 -4.3 12 -11.3 2.7 -11.3 2.7 -4.3  
[ INFO] [1570437712.790975869]: Wall distance: 1 m
[ INFO] [1570437712.791713847]: Cost function: Time
[ INFO] [1570437712.791750706]: v_max: 3, a_max: 1
[ INFO] [1570437712.797046686]: Sending visualization messages.
[ WARN] [1570437712.797091504]: Cannot send solution visualization because plan has not been made.
[ INFO] [1570437712.798463729]: Sensor model: frustum
[ INFO] [1570437712.798501364]: Lateral FOV: 0.84
[ INFO] [1570437712.798513305]: Altitude: 3
[ INFO] [1570437712.798522766]: Lateral overlap: 0.6
[ INFO] [1570437712.798532113]: Sweep distance: 1.07177
[ INFO] [1570437712.798741218]: Sweep single direction: 0
[ INFO] [1570437712.798772214]: Reset planner.
[ INFO] [1570437712.798780417]: Sensor model: frustum
[ INFO] [1570437712.798790769]: Lateral FOV: 0.84
[ INFO] [1570437712.798799048]: Altitude: 3
[ INFO] [1570437712.798806060]: Lateral overlap: 0.6
[ INFO] [1570437712.798813589]: Sweep distance: 1.07177
[ INFO] [1570437712.798841745]: Start creating sweep plan graph.
[coverage_planner-2] process has died [pid 2616, exit code -11, cmd /home/rsteiner/catkin_ws/devel/lib/polygon_coverage_ros/coverage_planner __name:=coverage_planner __log:=/home/rsteiner/.ros/log/83c9a626-e8da-11e9-a211-7c763585f93f/coverage_planner-2.log].
log file: /home/rsteiner/.ros/log/83c9a626-e8da-11e9-a211-7c763585f93f/coverage_planner-2*.log

**When wall_distance: 0.0 everything works fine.**

**Comment by rikba** [comment]
Thanks for the input. It should be fixed now. For more "deterministic" behavior I'd recommend to plan a polygon that has inflated obstacles in the first place. The polygon offsetting we are currently doing can result in cases where the resulting polygon is invalid and the offsetting is reduced or fully omitted.
