### ISSUE TITLE
ros coverage_planner: Buffer zone around polygons

### ISSUE THREAD

**Issue by nxdefiant** [ethz-asl/polygon_coverage_planning#33]
I wonder how to create a buffer zone/save margin around the polygons for the coverage_planner ros node. The hull should be reduced and each hole increased by an amount.

I tried to set wall_distance, but it does not seem to do anything.

**Comment by rikba** [comment]
Hi
you can indeed use the `wall_distance` parameter to shrink the hull / grow the holes. Here is the default polygon `roslaunch polygon_coverage_ros coverage_planner.launch` with

`wall_distance: 0.0`:
![rviz_screenshot_2020_02_10-08_52_36](https://user-images.githubusercontent.com/11293852/74130856-60af9300-4be3-11ea-8d2e-00b1df9f0e2b.png)
 
`wall_distance: 3.0`:
![rviz_screenshot_2020_02_10-08_55_42](https://user-images.githubusercontent.com/11293852/74130875-686f3780-4be3-11ea-9138-2f01d1a102ef.png)

But this currently only works if the input polygon with holes keeps the same topology, i.e., holes don't merge together, or the polygon is split into two entities. Thus if possible I would avoid the `wall_distance` parameter and account for the margin in the input polygon already.

**Comment by nxdefiant** [comment]
Thanks, I guess you are referring to this:

>  WARN] [1581361388.061421447]: Polygon offsetting changes topology. Reducing offsetting distance.

I'm now using [pythons shapely buffer() method](https://shapely.readthedocs.io/en/latest/manual.html#object.buffer) to reduce/increase the polygon sizes, it works so far.

**Comment by rikba** [comment]
Thanks for your feedback! Just for reference, we are using https://doc.cgal.org/latest/Straight_skeleton_2/index.html to offset the polygon.
