### ISSUE TITLE
wstool update

### ISSUE THREAD

**Issue by Sunjiahao111** [ethz-asl/polygon_coverage_planning#57]
HOW to handle this? sir? I'm confused with the *dependencies_https.rosinstall.* How to use this?
ssh: connect to host github.com port 22: Connection timed out
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。(Please confirm that you have the correct access rights and the warehouse exists. )

Exception caught during install: Error processing 'polygon_coverage_planning' : [polygon_coverage_planning] Checkout of git@github.com:ethz-asl/polygon_coverage_planning.git version v2.0.1 into /home/steven/catkin_ws/src/polygon_coverage_planning failed.

ERROR in config: Error processing 'polygon_coverage_planning' : [polygon_coverage_planning] Checkout of git@github.com:ethz-asl/polygon_coverage_planning.git version v2.0.1 into /home/steven/catkin_ws/src/polygon_coverage_planning failed.

**Comment by rikba** [comment]
Hi @Sunjiahao111 

maybe this is a broken internet connection?

> ssh: connect to host github.com port 22: Connection timed 

Otherwise, can you give me some feedback during which step of the [installation](ssh: connect to host github.com port 22: Connection timed ) it breaks?

Thanks for your feedback!

**Comment by Sunjiahao111** [comment]
> Hi @Sunjiahao111
> 
> maybe this is a broken internet connection?
> 
> > ssh: connect to host github.com port 22: Connection timed
> 
> Otherwise, can you give me some feedback during which step of the [installation](https://github.com/ethz-asl/polygon_coverage_planning#installation-on-ubuntu-1804-and-ros-melodic) it breaks?
> 
> Thanks for your feedback!

Hi, thank you sir
![图片](https://user-images.githubusercontent.com/87142468/132089926-1d6541d4-5e7a-43b5-b5a7-2fb1a5c59b44.png)
In this step, the first "wstool update"
![图片](https://user-images.githubusercontent.com/87142468/132089983-6912e7e3-3423-4bc8-83f3-1f1a33db1e8d.png)

steven@steven-ThinkPad-T480s:~/catkin_ws/src$ wstool update
/home/steven/.local/lib/python2.7/site-packages/wstool/config_yaml.py:74: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yamldata = yaml.load(stream)
[polygon_coverage_planning] Fetching git@github.com:ethz-asl/polygon_coverage_planning.git (version v2.0.1) to /home/steven/catkin_ws/src/polygon_coverage_planning
正克隆到 '/home/steven/catkin_ws/src/polygon_coverage_planning'...
ssh: connect to host github.com port 22: Connection timed out
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
Exception caught during install: Error processing 'polygon_coverage_planning' : [polygon_coverage_planning] Checkout of git@github.com:ethz-asl/polygon_coverage_planning.git version v2.0.1 into /home/steven/catkin_ws/src/polygon_coverage_planning failed.

ERROR in config: Error processing 'polygon_coverage_planning' : [polygon_coverage_planning] Checkout of git@github.com:ethz-asl/polygon_coverage_planning.git version v2.0.1 into /home/steven/catkin_ws/src/polygon_coverage_planning failed.

**Comment by rikba** [comment]
I think you are trying to use the ssh link but did not setup ssh keys in Github. Please try using the https checkout:

```
cd ~/catkin_ws/src
wstool init
wstool set --git polygon_coverage_planning https://github.com/ethz-asl/polygon_coverage_planning.git -v v2.0.1
wstool update
wstool merge polygon_coverage_planning/install/dependencies_https.rosinstall
wstool update
```

**Comment by rikba** [comment]
Closed due to inactivity.
