### ISSUE TITLE
Installation Info

### ISSUE THREAD

**Issue by FrGe2016** [ethz-asl/polygon_coverage_planning#60]
Hi

I would like to try it for my homemade ROS lawn mower but the installation is quite different from what i am used to and i would not like to create problems in my existing catkin_ws

Q1. Can the installation be made within another workspace without adaptations

Q2. Where and how i should download the dependencies for  dependencies.rosinstall

**Comment by rikba** [comment]
> Q1. Can the installation be made within another workspace without adaptations
Yes, you can build the package in a different workspace. I have a separate workspace for example containing only [polygon_coverage_planning](https://github.com/ethz-asl/polygon_coverage_planning), [cgal_catkin](https://github.com/ethz-asl/cgal_catkin) and [catkin_simple](https://github.com/catkin/catkin_simple).

> Q2. Where and how i should download the dependencies for dependencies.rosinstall
You can either use [ws_tool](https://github.com/ethz-asl/polygon_coverage_planning#installation-on-ubuntu-1804-and-ros-melodic) or you clone them manually.

```
cd ~
mkdir coverage_ws
cd coverage_ws
catkin init
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
catkin config --extend /opt/ros/melodic
mkdir src
cd src
git clone https://github.com/catkin/catkin_simple.git
git clone https://github.com/ethz-asl/cgal_catkin.git
git clone https://github.com/ethz-asl/polygon_coverage_planning.git
cd cgal_catkin
git checkout releases/CGAL-5.0.3
cd ../polygon_coverage_planning
git checkout v2.0.3
```

Make sure to install the [non-catkin dependencies](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/install/prepare-jenkins-slave.sh). Then you should be able to do `catkin build`.

Good luck with your project!

**Comment by FrGe2016** [comment]
Hi Rik

Thanks for your response. You have a very interesting package.

The installation went fine until :  *wstool update*

Here is a close up of the feedback at this step

***@***.***:~/coverage_ws/src$ wstool update
Prepare updating ***@***.***:ethz-asl/polygon_coverage_planning.git
(version None) to /home/francois/coverage_ws/src/polygon_coverage_planning
Url https://github.com/ethz-asl/polygon_coverage_planning.git does not
match ***@***.***:ethz-asl/polygon_coverage_planning.git requested.
*  (d)elete and replace, (a)bort, (b)ackup and replace, (s)kip: d*
[polygon_coverage_planning] Fetching
***@***.***:ethz-asl/polygon_coverage_planning.git
(version None) to /home/francois/coverage_ws/src/polygon_coverage_planning
Cloning into '/home/francois/coverage_ws/src/polygon_coverage_planning'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3'
to the list of known hosts.


***@***.*** ***@***.***>: Permission denied (publickey).fatal:
Could not read from remote repository.*
Please make sure you have the correct access rights
and the repository exists.
Exception caught during install: Error processing
'polygon_coverage_planning' : [polygon_coverage_planning] Checkout of
***@***.***:ethz-asl/polygon_coverage_planning.git version None into
/home/francois/coverage_ws/src/polygon_coverage_planning failed.

ERROR in config: Error processing 'polygon_coverage_planning' :
[polygon_coverage_planning] Checkout of
***@***.***:ethz-asl/polygon_coverage_planning.git
version None into /home/francois/coverage_ws/src/polygon_coverage_planning
failed.


*It is looking that the repository is restricted somehow*

*regards*


*Francois*

**Comment by rikba** [comment]
Hi Francois

I think that is because you are using the SSH link, i.e.,
```
wstool set --git polygon_coverage_planning git@github.com:ethz-asl/polygon_coverage_planning.git
```
but you do not have a [git ssh key setup](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). You can either setup the SSH key or use the https link instead:
```
wstool set --git polygon_coverage_planning https://github.com/ethz-asl/polygon_coverage_planning.git
```

Remember, if you use the https key you also need to use the dependencies_https.rosinstall.
```
wstool merge polygon_coverage_planning/install/dependencies_https.rosinstall
```

**Comment by FrGe2016** [comment]
Awesome, thanks!

I wave tried it with coverage_planner.launch
         The imported polygon is working well when a call the ROS service
<https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_msgs/srv/PlannerService.srv>
call 'rosservice call /coverage_planner/plan_path'

             But not in RVIZ, where i have the same issue as 36.
                               roslaunch polygon_coverage_ros
coverage_planner.launch      is having this problem

                   roslaunch polygon_coverage_ros
shortest_path_planner.launch is having this problem

                        After the polygon edition, it is very difficult to
generate
                            the starting point has to be clicked many times
b4 we have a feedback in the console
                                 (Selecting START from RVIZ PublishPoint
tool)

                             after a second selection of the Publish point
button, it is also a struggle to have the goal

                             then the generated path is just a line from
the start to the goal
                                   Number of waypoints: 3
                                   Start point: 25.4363 15.0461
                                   Goal point: 145.071 14.6242
                                   Altitude: 3 [m]
                                   Path length: 122.413 [m]

                               From what i have seen it is only working
with a Satellite background (i.e roslaunch polygon_coverage_ros
coverage_planner_satellite.launch is ok)

                               I have started a modified version of
"coverage_planner_satellite.rviz" ( removed the AerialMapDisplay add on and
added the local map display ) with my mobile robot simulator to provide the
map in replacement of  the satellite
*                               and it-is ok,*  ( This way i can draw above
my map generated with a cad drawing witch is good somehow but idealy i
would like to avoid the long process of making a drawing a scaling the pgn
image corectly )

                               If try the same exercise starting with a
modified config of "coverage_planner.rviz" ( replaced world frame with map
and added local map display) t*hen the problem is still there*

**Comment by FrGe2016** [comment]
Thanks for the feedback.

For now i have 2 workarounds:
        - Sending the one you gave me
        - Using roslaunch polygon_coverage_ros
coverage_planner_satellite.launch and a map published by the map server.

Then i can make it work, it is fine for me. But someone else could have the
problem.

Here are a few more questions:

         Question 1
          Is there an existing* setting of parameters to force the
direction of the sweeping*. ( in the exemple below it could be interesting
only horizontal paths )

[image: Screenshot from 2021-12-01 09-26-01.png]

         i know that sweep_single_direction: false gives me a mix of both
directions

         Question 2

         I would like to verify my understanding. For a lawn mower with a
0.5 m diameter blade. I would use this setting
                   sensor_model_type: 0 # [0: Line, 1: Frustum]
                   lateral_overlap: 0.1
                   lateral_footprint: 0.5 # Only for line sensor model.

                   with type 1 sensor, it would not be necessary to
evaluate  a specific z value to have the right distance between mowing paths


regards

Francois






Le mer. 1 déc. 2021, à 07 h 04, Rik Baehnemann ***@***.***> a
écrit :

**Comment by rikba** [comment]
> Question 1
>           Is there an existing* setting of parameters to force the
> direction of the sweeping*. ( in the exemple below it could be interesting
> only horizontal paths )

This is not implemented at the moment. But I think it's a useful feature. Opened a new issue https://github.com/ethz-asl/polygon_coverage_planning/issues/63

 

>          Question 2
> 
>          I would like to verify my understanding. For a lawn mower with a
> 0.5 m diameter blade. I would use this setting
>                    sensor_model_type: 0 # [0: Line, 1: Frustum]
>                    lateral_overlap: 0.1
>                    lateral_footprint: 0.5 # Only for line sensor model.

If you have 0.5m diameter blade your setting like this should be correct.

**Comment by FrGe2016** [comment]
Thanks for the feedback!

Le mer. 1 déc. 2021, à 10 h 55, Rik Baehnemann ***@***.***> a
écrit :
