### ISSUE TITLE
Unable to load type [polygon_coverage_msgs/PlannerService] error

### ISSUE THREAD

**Issue by sanderboers48** [ethz-asl/polygon_coverage_planning#64]
Hi,

First of all, thank you for creating this wonderful package. I hope you can help me with this problem I am having.

When I want to call the Plan_path service, I receive this error. 

`ERROR: Unable to load type [polygon_coverage_msgs/PlannerService].
Have you typed 'make' in [polygon_coverage_msgs]`

I tried to google this problem for solutions, but sadly I couldn't find one. Do you know how to resolve this error? Thanks in advance

**Comment by sanderboers48** [comment]
Alright, never mind... I am new to working with ROS and forgot to source the devel/setup.bash in the new terminal. It is working as it should now.

:|

**Comment by PhilipAmadasun** [comment]
@sanderboers48 I'm super confused on  how to use the package. I'm using a simulated robot, I'm not sure how to use this package for that, when I follow the instructions the rviz opens up but I get  GlobalStatuError
