### ISSUE TITLE
Can this package be used for differential drive robots?

### ISSUE THREAD

**Issue by DistroIII** [ethz-asl/polygon_coverage_planning#65]
Can this package work for differential drive robots(wheeled)?

**Comment by rikba** [comment]
The package will output a list of 2D waypoints. So I think it is very well usable for differential drive robots. The robots can either stop and turn at each waypoint or smooth out the trajectory.

However, this package requires an a priori known map and global positioning. Furthermore, with very cluttered environments, e.g., home environments with chairs etc., it is probably better to use approximate cellular decomposition methods, i.e., discretize the map and run a spanning tree like optimization.

This package use case is more GPS controlled coverage for aerial vehicles for example or ground robots in open, structured environments.

Feel free to reopen the issue if you have further questions or further specify your problem and give links to what you have been using in the end. I think this is useful information. Thank you!

**Comment by DistroIII** [comment]
@rikba I managed to create all the packages and catkin build. The instructions of how to use it though, really confused me:
[i] Firstly when I `roslaunch polygon_coverage_ros coverage_planner.launch`, Rivz open up but I get a global status error "Fixed Frame [world] does not exist". and TF warning "No transform from [base_footprint] to frame [world]. Am I to have launch some other files before this?
[ii] I'm using a simulated differential drive robot. I have a simulated world and I have the known map of the world. am I to manually make a representation of the map on RViz? 
As you can see, I don't even know where to begin. Can I have a more comprehensive instructions?
