### ISSUE TITLE
install dir

### ISSUE THREAD

**Issue by 1667** [ethz-asl/polygon_coverage_planning#7]
I can not find install dir in code.Is there any error in repository? thanks!

**Comment by rikba** [comment]
Hi @1667 

we are still porting the code. We plan to have a full working version end of next week.

**Comment by rikba** [comment]
Hi @1667 

I'd like to announce that the repo is in a usable state now.

**Comment by 1667** [comment]
Hi @rikba 
Yes,It's so cool! I have run it on Ubuntu16.04 yesterday. For Ubuntu16.04,I installed gcc-7 and export CC=/path/to/gcc-7 and CXX=/path/to/g++-7 when I built this project. 
Thanks.
