### ISSUE TITLE
Inquiry Continuation of #66 and #67

### ISSUE THREAD

**Issue by PhilipAmadasun** [ethz-asl/polygon_coverage_planning#70]
I am using a simulated turtlebot3. I 'roslaunch turtlebot3_gazebo turtlebot3_world.launch` to open up a simualted turtelbot3 in a world in gazebo.

I then `roslaunch polygon_coverage_ros coverage_planner.launch`. from issue #66 I have already changed 'world' to 'map' and I still get global status error and TF error. 
I don't know how to fix this error at all. from #66(my last unanswered response:"I changed the frame id to "map", I still get the global status error.
Is your explanation that I have to manually set the polygon of the map my
self? To do that, wouldn't I have to know the dimensions of the map to set
the points?, so I have to know the x,y,z values of the extremities of the
map?")

It is also not clear how to use the polygon selection, when I try to create a polygon, it isn't clear how to click away to finish it, no matter what I do, the polygon selction keeps adding edges to the previous polygon I was trying to create.

**Comment by PhilipAmadasun** [comment]
okay I figured out polygon selection, when I coverage_planner has made a plan, how do I then make the robot follow the plan?

**Comment by rikba** [comment]
@PhilipAmadasun I'm not familiar with the turtle bot simulation. But in principle you should be able to manually send waypoints to the turtle bot. Try this first.

To then send the list of waypoints that polygon_coverage_planning creates to the turtle bot you have to create a middle node. This node should select the next waypoint from the list, define a desired heading, send this waypoint to the turtle bot and observe whether the waypoint has been reached.

**Comment by PhilipAmadasun** [comment]
@rikba What script is responsible for creating the waypoint's in the first place?

What message type did you you use for the waypoints?

If I can just edit the script that generates the waypoints can't I just publish those waypoints from said script?

**Comment by rikba** [comment]
Hi @PhilipAmadasun 

> What script is responsible for creating the waypoint's in the first place?

The coverage_planner in [coverage_planner.launch](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/launch/coverage_planner.launch) creates the waypoints given the polygon and start and goal point.

> What message type did you you use for the waypoints?

The resulting waypointlist is published as [geometry_msgs/PoseArray](http://docs.ros.org/en/lunar/api/geometry_msgs/html/msg/PoseArray.html) on topic `/waypoint_list`.

> If I can just edit the script that generates the waypoints can't I just publish those waypoints from said script?

You could change the output message type here: https://github.com/ethz-asl/polygon_coverage_planning/blob/1056d54e41c31096b3bbb74e95c7d539a82b24f8/polygon_coverage_ros/src/polygon_planner_base.cc#L305-L326 but I would recommend to have your personal interface node that does the transformation to keep interdependencies small.

> How has your node been able to send way points to your robot generally?

The drone in the [video](https://www.youtube.com/watch?v=u1UOqdJoK9s) uses an additional [mission planner layer](https://github.com/ethz-asl/mav_findmine/tree/main/libs/fm_mission_planner) to select and visualize the polygon in a georeferenced frame, a [polynomial trajectory planner layer](https://github.com/ethz-asl/mav_findmine/tree/main/libs/fm_trajectories) that converts waypoint lists to dynamically feasible polynomial segments and a [state machine layer](https://github.com/ethz-asl/mav_findmine/tree/main/libs/fm_task_manager) that manages take off, trajectory parsing and landing. However, this interface is very platform dependent and thus not part of the 2D coverage planner.

> Would I have to know the dimensions of my map(As in the location of the extremities of the map) in order to create the polygons?

Yes, this planner requires knowledge of the map and obstacles in advance.

> Also, I was reading the accompanied paper and wanted to ask if the planner allows the robot to revisit regions of the map it has already covered?
No, this planner does not allow visiting the same polygon region a second time. You would either have to extend the optimization problem to duplicate the cluster, i.e., polygon region somehow in the [code](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_planners/src/graphs/sweep_plan_graph.cc#L89). Or you would have to call the planner a second time on the reduced problem, possible in combination with the [shortest path planner](https://github.com/ethz-asl/polygon_coverage_planning/blob/14951b96bd6e840fed9cf21aace8a2043be5fd15/polygon_coverage_ros/launch/shortest_path_planner.launch) to move to the desired starting position. But depending on your problem setup and complexity it may be worth to look into discrete coverage or exploration planning approaches or to start your own optimization problem, possibly using some of the geometric and graph solving components of this repository.
