### ISSUE TITLE
Large terrain takes very very long time to plan coverage path

### ISSUE THREAD

**Issue by qiangsun89** [ethz-asl/polygon_coverage_planning#74]
Hi，
Large terrain takes a long time to plan a coverage path. How do optimize algorithms to improve computational efficiency?
[example_polygon_epfl_simple.txt](https://github.com/ethz-asl/polygon_coverage_planning/files/9495113/example_polygon_epfl_simple.txt)
Here is an example of the large terrain.

**Comment by rikba** [comment]
@stlucas44 can you have a look what is the bottle neck with this polygon?
