### ISSUE TITLE
error: Goal node is not at back of solution

### ISSUE THREAD

**Issue by qiangsun89** [ethz-asl/polygon_coverage_planning#75]
Hi,
   When I use coverage planner, I meet the error as below.

[ERROR] [1663640010.389049927]: Goal node is not at back of solution.
[ERROR] [1663640010.389990257]: Failed solving graph.
[ERROR] [1663640010.390038090]: Failed calculating plan.

Could you please give me advices about how to fix this issue.
Thanks

my coverage planner yaml is
-------------------------------
decomposition_type: 0 # [0: Boustrophedon, 1: Trapezoidal]
cost_function_type: 1 # [0: Euclidean Distance, 1: Time, 2: Number of Waypoints]
v_max: 0.4 # Only for time optimization.
a_max: 0.2 # Only for time optimization.
wall_distance: 0.0
offset_polygons: false
sweep_single_direction: true

# Sensor model.
sensor_model_type: 1 # [0: Line, 1: Frustum]
lateral_overlap: 0.6
lateral_footprint: 1.0 # Only for line sensor model.
lateral_fov: 0.84 # Only for frustum sensor model.

latch_topics: true

publish_plan_on_planning_complete: false
publish_visualization_on_planning_complete: true
set_start_goal_from_rviz: true
set_polygon_from_rviz: true
-------------------------------------
polygons is 
[example_polygon_epfl_simple.txt](https://github.com/ethz-asl/polygon_coverage_planning/files/9603782/example_polygon_epfl_simple.txt)

**Comment by rikba** [comment]
Hi @qiangsun89 

Thanks for your example. You are really putting this algorithm on a limit. This approach has a problem if the Boustrophedon decomposition has really different cell sizes. In your example you sometimes have numerically huge cells to cover by the robot and then very small details. This makes the adjacency matrix which describes the GTSP ill conditioned and the solver fails. I tried to improve the behavior in https://github.com/ethz-asl/polygon_coverage_planning/pull/77

If the problem remains I have the following suggestions.

1. Only optimize over a [single sweeping direction](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/cfg/coverage_planner.yaml#L7) `sweep_single_direction: true`. This avoids extremely similar cost values for the same cell.
2. Consider different cost such as [number of waypoints](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/cfg/coverage_planner.yaml#L2) `cost_function_type: 2`. The cost is then always in the low integer values anyways which makes it numerically stable.
3. For large environments have [large robot footprints](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/cfg/coverage_planner.yaml#L12) if possible `lateral_footprint: 100.0`. This will also keep the cost values in the low range.
4. Design simple polygons (few details/concaves/holes) if possible in conjunction with a single sweeping direction (1.). This will keep the cost matrix evenly balanced.

**Comment by rikba** [comment]
![rviz_screenshot_2022_09_23-20_21_44](https://user-images.githubusercontent.com/11293852/192046812-a1fae614-cab1-4262-a907-7515d8a9ed12.png)

**Comment by PhilipAmadasun** [comment]
@rikba What exactly is lateral footprint and lateral FOV?
