### ISSUE TITLE
Question about video presentation.

### ISSUE THREAD

**Issue by PhilipAmadasun** [ethz-asl/polygon_coverage_planning#81]
On the video presentation you guys made for youtube, you imported the picture of the grass field into rviz. How were you able to do that? I want to import the png file of the map I want to cover so I can do the same thing.

**Comment by rikba** [comment]
Cool! What exactly do you mean by "glass filed into rviz"?
Can you give me a time stamp of the video?

**Comment by PhilipAmadasun** [comment]
@rikba I meant "grass field" not "glass filed" sorry

**Comment by PhilipAmadasun** [comment]
@rikba I'll check to see if it runs, I still need more explanation with the lateral FOV problem, I continued the conversation on that thread just now.

**Comment by PhilipAmadasun** [comment]
@rikba is lateral footprint the same as sensor footprint? if so what is the unit, is it m^2?
