### ISSUE TITLE
Can't echo /waypoint_list

### ISSUE THREAD

**Issue by bdime-009** [ethz-asl/polygon_coverage_planning#86]
rostopic echo /waypoint_list informs me it is not published yet.
How to find the pose array generated .

**Comment by rikba** [comment]
You have to call the service call `rosservice call /coverage_planner/publish_path_points` additionally after planning. This has been a safety feature to not send the plan immediately to the robot.

However, you can activate, that the planner immediately sends the waypoints with this parameter: https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/cfg/coverage_planner.yaml#L17

I updated the [README](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/README.md#coverage-planning).

**Comment by bdime-009** [comment]
Excellent.Thanks, Rik.
