### ISSUE TITLE
line distance

### ISSUE THREAD

**Issue by muratkoc503** [ethz-asl/polygon_coverage_planning#88]
Hello thanks for repository.it's very good. How i adjust line-to-line distance (sweep distance)?

![1(1)](https://user-images.githubusercontent.com/75611653/222886569-614b83fe-da24-4ed8-b52f-e75c0978bbde.jpg)

**Comment by rikba** [comment]
Hi there, 

there are two ways to change the line distance in the [sensor model configuration](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/cfg/coverage_planner.yaml#L10-L13).

1. You choose a camera model `sensor_model_type: 1 # [0: Line, 1: Frustum]`. Then the distance is calculated from the `lateral_overlap`, `lateral_fov`, and [polygon z-component (height)](https://github.com/ethz-asl/polygon_coverage_planning/blob/master/polygon_coverage_ros/cfg/polygons/example_polygon_epfl_simple.yaml#L13). See also https://github.com/ethz-asl/polygon_coverage_planning/issues/82#issuecomment-1308953913
2. You choose `sensor_model_type: 0 # [0: Line, 1: Frustum]`. Then the line distance is only defined by `lateral_footprint`, e.g., : `lateral_footprint: 5.0 # Only for line sensor model.` will give `5.0m` spacing.
