### ISSUE TITLE
using with map (map.pgm or occupancy grid map)

### ISSUE THREAD

**Issue by muratkoc503** [ethz-asl/polygon_coverage_planning#89]
i want to use planner with map (map.pgm). How to use planner with map? Must i convert obstacles in Occupancy Grid Map to polygon? How i use this planner in real time? Thanks.

**Comment by rikba** [comment]
Hi Murat

Yes, you would have to convert the Occupancy Grid Map to a polygon map somehow.

In general, you can set a new polygon via `rosservice call /coverage_planner/set_polygon` and plan a new path via `rosservice call /coverage_planner/plan_path`. However, this planner is intended for more of a static map. If you constantly update the map and the plan it will not really be continuous. Let's say you could update the plan probably once per room, but not with 5 Hz. If you have fast update rates, you probably want to use some spanning tree like algorithm that works on a discrete map.

**Comment by muratkoc503** [comment]
thanks. i understood clearly.
